### ISSUE TITLE
Plasma 6 version only works when holding the mouse button

### ISSUE THREAD

**Issue by Bingo90** [HimDek/Overview-Widget-for-Plasma#3]
A simple click doesn't work, I have to hold left click and drag my cursor off the icon for overview to open.

Additionally, it messes up the panel icons until I edit the panel.

**Comment by Anarcraft** [comment]
I've noticed the first issue here is fixed.  The second issue may be due to a bug with the icon being a small size instead of what is should be according to your panel size.

**Comment by Bingo90** [comment]
> I've noticed the first issue here is fixed. The second issue may be due to a bug with the icon being a small size instead of what is should be according to your panel size.

Doesn't look like the first issue's fixed - I just installed the most recent publicly available version and it still doesn't work

**Comment by Anarcraft** [comment]
> Doesn't look like the first issue's fixed - I just installed the most recent publicly available version and it still doesn't work

I'm on Arch Linux (LTS and Zen kernels) using Wayland and Plasma 6.0.3 and working for me on multiple machines.  Does yours differ than mine?

**Comment by Bingo90** [comment]
Regular non-LTS kernel and I'm using X11. Plasma's also 6.0.3 though

**Comment by Anarcraft** [comment]
Arch or another distro?

**Comment by Bingo90** [comment]
Arch too

**Comment by Anarcraft** [comment]
I definitely had this issue when Plasma 6 first came out but then a few weeks later it started working so I figured it was an update to the widget or Plasma that fixed it.  I tried enabling multiple virtual desktops and changing the settings for the desktop effect and it continues to work.  I've used a mouse and touchpad for clicking.  I'm currently out of ideas.

**Comment by Anarcraft** [comment]
You could try it in a fresh user account and see if it still happens.

**Comment by HimDek** [comment]
Check if https://github.com/HimDek/Overview-Widget-for-Plasma/issues/6#issuecomment-2094522178 works.

**Comment by Bingo90** [comment]
> Check if [#6 (comment)](https://github.com/HimDek/Overview-Widget-for-Plasma/issues/6#issuecomment-2094522178) works.

Yeah, that does open the overview!

**Comment by LMauricius** [comment]
Was the issue in title itself fixed? Using the version from the store, the overview still closes when I release the mouse button. I have to drag the cursor off the icon and then release the button to work.

**Comment by gianmarcogg03** [comment]
I'm on Fedora KDE 40 with Plasma 6.1 (Wayland) and the button works only if you click twice, because the first click does not go through while the second one does.

**Comment by LMauricius** [comment]
That's funny. It certainly doesn't work for me if I click it twice. In fact, on KDE Neon it seems pretty consistent that releasing the mouse button while hovering the button stops the effect (even if the animation didn't even start yet).
